# Generated by Django 4.2.1 on 2023-05-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoner_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonermodel',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
